export default {
  SIGN_IN: 'SIGN_IN',

  INIT_FORM: 'INIT_FORM',
  INIT_FIELD: 'INIT_FIELD',

  CHANGE_FIELD_VALUE: 'CHANGE_FIELD_VALUE',
  VALIDATE_FIELD: 'VALIDATE_FIELD',
  SET_FIELD_VALIDATION_ERRORS: 'SET_FIELD_VALIDATION_ERRORS',

  VALIDATE_FORM: 'VALIDATE_FORM',
  SET_FROM_VALIDATION_ERRORS: 'SET_FROM_VALIDATION_ERRORS',
  SUBMIT_FORM: 'SUBMIT_FORM',
};
